### ISSUE TITLE
Don't work with flutter_html

### ISSUE THREAD

**Issue by pdechanoz** [ijashuzain/y_player#7]
Hello,
I'm trying to use with flutter_html, and it's don't work.
My code :
` return Html(
      data: content,
      shrinkWrap: true,
    extensions: [
        const TableHtmlExtension(),
        const SvgHtmlExtension(),
        const AudioHtmlExtension(),
        TagExtension(
          tagsToExtend: {"iframe"},
          builder: (ExtensionContext eContext) {
            final String source = eContext.attributes['src'].toString();
            if (source.contains('youtu')  {
              return YPlayer( youtubeUrl: source, );
            } else {
            return Container();
          },),
]);`

The error: 
════════ Exception caught by widgets library ═══════════════════════════════════
The following _Exception was thrown building _WidgetSpanParentData:
Exception: MediaKit.ensureInitialized must be called before using any API from package:media_kit.

The relevant error-causing widget was:
    Html Html:file:lib/views/html_body/html_body.dart:57:12

When the exception was thrown, this was the stack:
#0      NativeLibrary.path (package:media_kit/src/player/native/core/native_library.dart:20:7)
#1      new NativePlayer (package:media_kit/src/player/native/player/real.dart:62:63)
#2      new Player (package:media_kit/src/player/player.dart:113:18)
#3      new YPlayerController (package:y_player/src/y_player_controller.dart:32:15)
#4      YPlayerState.initState (package:y_player/src/y_player_main.dart:87:19)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748:55)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
...     Normal element mounting (13 frames)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#20     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#21     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (25 frames) ...
etc ...

**Comment by ijashuzain** [comment]
Have initialised `YPlayer` by adding `YPlayerInitializer.ensureInitialized()` in `main()` ?

**Comment by pdechanoz** [comment]
Hello,
After initialized Yplayer it'work !
Thanks
