### ISSUE TITLE
Explode new update | muxed is empty | video is without audio | streams has video url without audio

### ISSUE THREAD

**Issue by HKTareen** [ijashuzain/y_player#8]
in explode new update 2.3.0  we are stuck now

**Comment by ijashuzain** [comment]
Yes, muxed streams are deprecated by youtube. It's not from youtube_explode team itself. Here we have managed to find a solution for that issue for playing video in latest version of `YPlayer`

Can you share more details if you are facing any issue by using `YPlayer` ?

**Comment by HKTareen** [comment]
Actually i want muxed stream only which is fulfilled by the explode as that is giving 360p video so its okey for me
